chore: update builtin generation

diff --git a/.github/workflows/lint-go.yaml b/.github/workflows/lint-go.yaml
--- a/.github/workflows/lint-go.yaml
+++ b/.github/workflows/lint-go.yaml
@@ -17,6 +17,13 @@ jobs:
         with:
           go-version: '1.22'
           cache: false
+      - name: Go Generate
+        run: go generate ./...
+
+      - name: Check `builtins` directory
+        # if it has any changes in the 'builtins' dir after running `go generate`, echo an error and fail the workflow
+        run: git diff --exit-code builtin/gen || (echo "\n\n\nbuiltin/gen directory is not up to date, run 'go generate ./...' to update it" && exit 1)
+
       - name: golangci-lint
         uses: golangci/golangci-lint-action@v6
         with:
