added compiled folder

diff --git a/.github/workflows/lint-go.yaml b/.github/workflows/lint-go.yaml
--- a/.github/workflows/lint-go.yaml
+++ b/.github/workflows/lint-go.yaml
@@ -18,6 +18,12 @@ jobs:
           go-version: '1.23'
           cache: false
 
+      - name: Check `builtins` directory
+        # if it has any changes in the 'builtins' dir after running `go generate`, echo an error and fail the workflow
+        run: |
+          go generate ./builtin/gen
+          git diff --exit-code builtin/gen || (echo "\n\n\nbuiltin/gen directory is not up to date, run 'go generate ./...' to update it" && exit 1)
+
       - name: Check `modernize` (code style)
         run: |
           go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@v0.18.1 ./...
