feat: verify tags/releases

diff --git a/.github/workflows/on-release.yaml b/.github/workflows/on-release.yaml
--- a/.github/workflows/on-release.yaml
+++ b/.github/workflows/on-release.yaml
@@ -1,15 +1,44 @@
 name: Release CI
 
 on:
-  release:
-    types:
-      - released
+  push:
+    tags:
+      - 'v*.*.*'
+      - '!v*.*.*-rc*'
 
 jobs:
+  validate:
+    runs-on: ubuntu-latest
+    name: Validate Release
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
-  run-unit-tests:
-    name: Run Unit Tests
-    uses: ./.github/workflows/test.yaml
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20'
+
+      - name: Validate Tag
+        run: |
+          node -e "if (!/^v\d+\.\d+\.\d+$/.test('${{ github.ref_name }}')) { console.error('Invalid version provided');process.exit(1);}"
+
+      - name: Validate VERSION
+        run: |
+          if [ "$(cat cmd/thor/VERSION)" != "${{ github.ref_name }}" ]; then
+            echo "VERSION file does not match tag"
+            exit 1
+          fi
+
+      - name: Validate Release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          prerelease=$(gh release view ${{ github.ref_name }} --json isPrerelease | jq -r '.isPrerelease')
+          if [ "$prerelease" != "false" ]; then
+            echo "Tag is not an official release"
+            exit 1
+          fi
 
   publish-docker-image:
     name: Publish Docker Image
@@ -17,6 +46,7 @@ jobs:
     secrets: inherit
     needs:
       - run-unit-tests
+      - validate
     permissions:
       contents: read
       packages: write
